# Paths for the birds dataset:
birds_images_path: 
birds_embedding_path: 
birds_text_path: 
birds_dataset_path: 
val_split_path: 
train_split_path: 
test_split_path: 


# Paths for the flowers dataset:
flowers_images_path: 
flowers_embedding_path: 
flowers_text_path: 
flowers_dataset_path: 
flowers_val_split_path: 
flowers_train_split_path: 
flowers_test_split_path: 